config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    # resources :purchases, only: [:index, :create, :show]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    resources :purchases, only: [:index, :create] do
      collection do
        post 'pay'
        get 'done'
      end
    end
  end
  resources :users, only: [:show] do
    resources :residences, only: [:create, :index]
    resources :card, only: [:new, :index] do
      collection do
        post 'pay', to: 'card#pay'
        delete 'delete', to: 'card#delete'
      end
    end
  end
  root "items#index"
  
  resources :categories, only: [:index]
  
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  require 'payjp'

  before_action :set_item
  before_action :set_card
  before_action :move_to_login, only:[:index, :pay, :done, ]

  def index
    @itemId = params[:item_id]
    session[:item_id] = params[:item_id]
    @purchaseId = params[:id]
    if current_user.residence.present?
      @residence = Residence.find_by(user_id: current_user.id)
    else
      @residence = Residence.new
    end

    card = set_card
    if card.blank?

    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @default_card_brand = @default_card_information.brand      
      case @default_card_brand
      when "Visa"
        @default_card_src = "visa.png"
      when "JCB"
        @default_card_src = "jcb.png"
      when "MasterCard"
        @default_card_src = "master.png"
      when "American Express"
        @default_card_src = "american.png"
      when "Diners Club"
        @default_card_src = "dinersclub.png"
      when "Discover"
        @default_card_src = "discover.png"
      end
    end
  end
  
  def pay
    card = set_card
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    Payjp::Charge.create(
    amount: @item.price, 
    customer: card.customer_id, 
    currency: 'jpy', 
    )
    redirect_to action: 'done'
  end

  def done
    @itemId = params[:item_id]
    @residence = Residence.find_by(user_id: current_user.id)
    @item.update(status: 0)
    card = set_card
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    customer = Payjp::Customer.retrieve(card.customer_id)
    @default_card_information = customer.cards.retrieve(card.card_id)
    @default_card_brand = @default_card_information.brand      
    case @default_card_brand
    when "Visa"
      @default_card_src = "visa.png"
    when "JCB"
      @default_card_src = "jcb.png"
    when "MasterCard"
      @default_card_src = "master.png"
    when "American Express"
      @default_card_src = "american.png"
    when "Diners Club"
      @default_card_src = "dinersclub.png"
    when "Discover"
      @default_card_src = "discover.png"
    end
  end

  private
  def residence_params
    params.require(:residence).permit(:family_name, :last_name, :j_family_name, :j_last_name, :postcode, :prefecture, :city, :block).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def set_card
    Card.where(user_id: current_user.id).first
  end

  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end

end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/done.html.haml
.purchase
  .purchase__inner
    .purchase__inner__top
      = link_to root_path  do
        = image_tag("material/logo/logo.png", class: 'purchase__inner__top__logo')
    .purchase__inner__main
      .purchase__inner__main__alert
        .purchase__inner__main__alert__top
          .purchase__inner__main__alert__top__clock
            = icon("far", "clock") 
          .purchase__inner__main__alert__top__sentence 発送をお待ちください
        %p.p.purchase__inner__main__alert__sub
          出品者からの発送通知をお待ちください
      %h1.purchase__inner__main__confirmation
        購入が完了しました
      .purchase__inner__main__item
        - objects = @item.item_images
        - first_image = objects.first 
        = image_tag first_image.image.url, class: 'purchase__inner__main__item__image'
        %ul.purchase__inner__main__item__description
          %li.purchase__inner__main__item__description__name #{@item.name}
          %li
            %ul.purchase__inner__main__item__description__money
              %li.purchase__inner__main__item__description__money__money ¥#{@item.price.to_s(:delimited)}（税込）
              %li.purchase__inner__main__item__description__money__text 送料込み
      .purchase__inner__main__form
        .purchase__inner__main__form__cost
          %ul.purchase__inner__main__form__cost__box
            %li.purchase__inner__main__form__cost__box__head 支払い金額
            %li.purchase__inner__main__form__cost__box__amount ¥#{@item.price.to_s(:delimited)}
        .purchase__inner__main__form__shipping
          %h2.purchase__inner__main__form__shipping__title 配送先
          %p 〒#{@residence.postcode}
          %p #{@residence.prefecture}#{@residence.city}#{@residence.block}#{@residence.building}
          %p #{@residence.family_name}#{@residence.last_name}
        .purchase__inner__main__form__pay
          %h2.purchase__inner__main__form__pay__title 支払い方法
          = "**** **** **** " + @default_card_information.last4 
          %br
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
          %br
          = image_tag "material/credit/#{@default_card_src}", width: '40', height: '25', alt: @default_card_brand, id: "card_image"
      .purchase__inner__main__after
        .purchase__inner__main__after__title
          発送通知後の流れ
        .purchase__inner__main__after__icons
          = icon("fas", "laugh", class: "laugh")
          = icon("fas", "meh", class: "meh")
          = icon("fas", "frown", class: "frown")
        .purchase__inner__main__after__content
          商品を受け取ったら
          %br
          出品者の評価をしましょう。
          %br
          購入代金が出品者に振り込まれます。
          %br
          評価後に取引は完了です。
        .purchase__inner__main__after__link
          = link_to 'マイページへもどる', user_path(current_user.id)

app/views/purchases/index.html.haml
.purchase
  = render "/shared/sub_header"
  .purchase__inner
    .purchase__inner__main
      %h1.purchase__inner__main__confirmation
        購入内容の確認
      .purchase__inner__main__item
        - objects = @item.item_images
        - first_image = objects.first 
        = image_tag first_image.image.url, class: 'purchase__inner__main__item__image'
        %ul.purchase__inner__main__item__description
          %li.purchase__inner__main__item__description__name #{@item.name}
          %li
            %ul.purchase__inner__main__item__description__money
              %li.purchase__inner__main__item__description__money__money ¥#{@item.price.to_s(:delimited)}（税込）
              %li.purchase__inner__main__item__description__money__text 送料込み

      = form_with(url: pay_item_purchases_path(item_id: @itemId), action: :pay, method: :post, model: @purchase, class: 'purchase__inner__main__form', local: true) do |f|
        .purchase__inner__main__form__cost
          %ul.purchase__inner__main__form__cost__box
            %li.purchase__inner__main__form__cost__box__head 支払い金額
            %li.purchase__inner__main__form__cost__box__amount ¥#{@item.price.to_s(:delimited)}
          = label_tag :use_point ,class: 'purchase__inner__main__form__cost__usepoint' do
            = f.check_box :use_point, class: 'purchase__inner__main__form__cost__usepoint__button'
            %p.purchase__inner__main__form__cost__usepoint__text ポイントを使用 (所持ポイント: P0)

        .purchase__inner__main__form__payment
          - if @default_card_information.blank?
            %ul
              %li.residence-title 支払い方法
              %li.register-button
                = icon("fas", "plus-circle")
                = link_to new_user_card_path(user_id: current_user.id) do
                  登録してください
          - else
            %ul.data-exists__header
              %li.card-title 支払い方法
              %li.data-exists__header__modify
                = link_to  new_user_card_path(user_id: current_user.id) do
                  変更する
            = "**** **** **** " + @default_card_information.last4 
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            %br
            = image_tag "material/credit/#{@default_card_src}", width: '40', height: '25', alt: @default_card_brand, id: "card_image"

        .purchase__inner__main__form__shipping
          - if @residence.new_record?
            %ul
              %li.residence-title 配送先
              %li.register-button
                = icon("fas", "plus-circle")
                = link_to user_residences_path(user_id: current_user.id) do
                  登録してください
          - else
            %ul.data-exists__header
              %li.residence-title 配送先
              %li.data-exists__header__modify
                = link_to user_residences_path(user_id: current_user.id) do
                  変更する
            %ul.residence-data
              %li 〒#{@residence.postcode}
              %li
                %ul.residence-data__address
                  %li.residence-data__address__item #{@residence.prefecture}
                  %li.residence-data__address__item #{@residence.city}
                  %li.residence-data__address__item #{@residence.block}
                  %li.residence-data__address__item #{@residence.building}
              %li
                %ul.residence-data__name
                  %li.residence-data__name__item #{@residence.family_name}
                  %li.residence-data__name__item #{@residence.last_name}

        .purchase__inner__main__form__buy
          - if @default_card_information && @residence
            = f.button '購入する', class: 'purchase__inner__main__form__buy__button'
          -else
            .purchase__inner__main__form__buy__button__not
              必要な情報を入力してください
            
    .purchase__inner__footer
      = render "/shared/sub_footer"

app/views/purchases/show.html.haml
.purchase
  .purchase__inner
    .purchase__inner__top
      = image_tag("material/logo/logo.png", class: 'purchase__inner__top__logo')
    .purchase__inner__main
      %h1.purchase__inner__main__confirmation
        購入内容の確認
      .purchase__inner__main__item
        = image_tag("material/icon/member_photo_noimage_thumb.png", class: 'purchase__inner__main__item__image')
        %ul.purchase__inner__main__item__description
          %li.purchase__inner__main__item__description__name ディズニーTシャツ3点セット
          %li
            %ul.purchase__inner__main__item__description__money
              %li.purchase__inner__main__item__description__money__money ¥1,600（税込）
              %li.purchase__inner__main__item__description__money__text 送料込み
      -#  form bigin
      = form_with(model: @purchase, class: 'purchase__inner__main__form', local: true) do |f|
        .purchase__inner__main__form__cost
          %ul.purchase__inner__main__form__cost__box
            %li.purchase__inner__main__form__cost__box__head 支払い金額
            %li.purchase__inner__main__form__cost__box__amount ¥1,600
          -# .purchase__inner__main__form__cost__usepoint
          = label_tag :use_point ,class: 'purchase__inner__main__form__cost__usepoint' do
            = f.check_box :use_point, class: 'purchase__inner__main__form__cost__usepoint__button'
            %p.purchase__inner__main__form__cost__usepoint__text ポイントを使用 (所持ポイント: P0)
        .purchase__inner__main__form__payment
          %h2 支払い方法
          %p.register-button
            = icon("fas", "plus-circle")
            登録してください
        .purchase__inner__main__form__shipping
          %h2 配送先
          %p.register-button
            = icon("fas", "plus-circle")
            登録してください
        .purchase__inner__main__form__buy
          = f.button '購入する', class: 'purchase__inner__main__form__buy__button'
      -#  form end
    .purchase__inner__footer
      %ul.purchase__inner__footer__list
        %li.purchase__inner__footer__list__privacy
          = link_to "#" do
            プライバシーポリシー
        %li
          = link_to "#" do
            メルカリ利用規約
        %li.purchase__inner__footer__list__disp
          = link_to "#" do
            特定商取引に関する表記
      .purchase__inner__footer__logo
        = link_to root_path do
          = image_tag("material/logo/logo.png", class: 'purchase__inner__footer__logo__image')
        %p ©︎ FURIMA