config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    # resources :purchases, only: [:index, :create, :show]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    resources :purchases, only: [:index, :create] do
      collection do
        post 'pay'
        get 'done'
      end
    end
  end
  resources :users, only: [:show] do
    resources :residences, only: [:create, :index]
    resources :card, only: [:new, :index] do
      collection do
        post 'pay', to: 'card#pay'
        delete 'delete', to: 'card#delete'
      end
    end
  end
  root "items#index"
  
  resources :categories, only: [:index]
  
end

app/views/shared/_footer.html.haml
.footer 
  .footer__contents
    .footer__contents--content
      .list 
        .list__title FURIMAについて
        .list__links
          = link_to "会社概要（運営会社）", "#", class: "link"
          = link_to "プライバシーポリシー", "#", class: "link"
          = link_to "FURIMA利用規約", "#", class: "link"
          = link_to "ポイントに関する特約", "#", class: "link"

    .footer__contents--content
      .list
        .list__title FURIMAを見る

        .list__links
          = link_to "カテゴリー一覧", categories_path, class: "link"
          = link_to "ブランド一覧", "#", class: "link"

    .footer__contents--content
      .list
        .list__title ヘルプ＆ガイド
        .list__links
          = link_to "FURIMAガイド", "#", class: "link"
          = link_to "FURIMAロゴ利用ガイドライン", "#", class: "link"
          = link_to "お知らせ", "#", class: "link"
    
  .footer__logo
    = link_to root_path do
      = image_tag 'material/logo/logo-white.png', class: "logo-btn"
  
  %p.copyright © FURIMA

app/views/shared/_header.html.haml
.header
  .header__mask
    .header__mask__menu
      .header__mask__menu__top
        = link_to root_path do
          = image_tag("material/logo/logo.png", class: 'header__mask__menu__top__icon')
        .header__mask__menu__top__search
          = form_with(model: @message, class: 'header__mask__menu__top__search__form', local: true) do |form|
            = form.search_field :content, placeholder: '何かお探しですか？', class: 'header__mask__menu__top__search__form__text-field'
            = icon("fa", "search", class: 'header__mask__menu__top__search__form__icon')
      .header__mask__menu__nav-box
        %ul.header__mask__menu__nav-box__left
          = link_to categories_path, class: 'header__mask__menu__nav-box__left__item' do
            = image_tag("material/icon/icon_category.png", class: 'header__mask__menu__nav-box__left__item__icon')
            %li.header__mask__menu__nav-box__left__item__parent.nav-search
              カテゴリーから探す
              %ul.header__mask__menu__nav-box__left__item__parent__child
                - @parents.each do |parent|
                  %li.nav-search
                    #{parent.name}
                    %ul.header__mask__menu__nav-box__left__item__parent__child__gchild
                      - children = parent.children
                      - children.each do |child|
                        %li.nav-search
                          #{child.name}
                          %ul.header__mask__menu__nav-box__left__item__parent__child__gchild__ggchild
                            - grandchildren = child.children
                            - grandchildren.each do |grandchild|
                              %li.nav-search
                                #{grandchild.name}
          = link_to "#", class: 'header__mask__menu__nav-box__left__item' do
            = image_tag("material/icon/icon_brand.png", class: 'header__mask__menu__nav-box__left__item__icon')
            %li.header__mask__menu__nav-box__left__item__parent.nav-search
              ブランドから探す
              %ul.header__mask__menu__nav-box__left__item__parent__child
                %li.nav-search
                  test1
                  %ul.header__mask__menu__nav-box__left__item__parent__child__gchild
                    %li.nav-search
                      test2
                      %ul.header__mask__menu__nav-box__left__item__parent__child__gchild__ggchild
                        %li.nav-search
                          test3
        
        - if user_signed_in?
          %ul.header__mask__menu__nav-box__right
            %li.header__mask__menu__nav-box__right__mask
              = link_to "#" ,class: 'nav-menu' do
                = icon("far", "heart", class: 'header__mask__menu__nav-box__right__mask__icon')
                %p.header__mask__menu__nav-box__right__mask__list いいね！一覧
            %li.header__mask__menu__nav-box__right__mask
              = link_to "#" ,class: 'nav-menu' do
                = icon("far", "bell", class: 'header__mask__menu__nav-box__right__mask__icon')
                %p.header__mask__menu__nav-box__right__mask__list お知らせ
            %li.header__mask__menu__nav-box__right__mask
              = link_to "#" ,class: 'nav-menu' do
                = icon("fa", "check", class: 'header__mask__menu__nav-box__right__mask__icon')
                %p.header__mask__menu__nav-box__right__mask__list やることリスト
            %li.header__mask__menu__nav-box__right__mask.nav-menu.header__mask__menu__nav-box__right__mask--mypage
              = link_to  user_path(current_user.id), class: 'nav-menu' do
                = icon("far", "user", class: 'header__mask__menu__nav-box__right__mask__icon')
                %p.header__mask__menu__nav-box__right__mask__list マイページ
              = render partial: 'shared/popup/popup_mypage.html.haml'
        - else
          %ul.header__mask__menu__nav-box__right--notlogin
            %li.header__mask__menu__nav-box__right--notlogin__mask
              = link_to new_user_registration_path, class: 'sign_up-button' do
                %p.header__mask__menu__nav-box__right--notlogin__mask__list 新規会員登録
            %li.header__mask__menu__nav-box__right--notlogin__mask
              = link_to user_session_path, class: 'sign_in-button' do
                %p.header__mask__menu__nav-box__right--notlogin__mask__list ログイン
  .header__nav-mask
    %ul.header__nav-mask__inner
      = link_to "#", class: 'header__nav-mask__inner__item' do
        %li メルカリ >
      - if user_signed_in?
        = link_to user_path(current_user.id), class: 'header__nav-mask__inner__item' do
          %li マイページ
       

app/views/shared/_mypage-left.html.haml
.mypage__main__mask__left
  %ul.mypage__main__mask__left__nav-list
    = link_to user_path(current_user.id), class: 'mypage__main__mask__left__nav-list__item mypage__main__mask__left__nav-list__item' do 
      %li マイページ
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li お知らせ
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li やることリスト
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li いいね！一覧
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to new_item_path, class: 'mypage__main__mask__left__nav-list__item' do
      %li 出品する
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li 出品した商品-出品中
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li 出品した商品-取引中
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li 出品した商品-売却済み
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li 購入した商品-取引中
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li 購入した商品-過去の取引
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li ニュース一覧
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li 評価一覧
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li ガイド
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li お問い合わせ
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
  %h3.mypage__main__mask__left__nav-head
    メルペイ
  %ul.mypage__main__mask__left__nav-list
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li 売上・振り込み申請
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li ポイント
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
  %h3.mypage__main__mask__left__nav-head
    設定
  %ul.mypage__main__mask__left__nav-list
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li プロフィール
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to user_residences_path(current_user.id), class: 'mypage__main__mask__left__nav-list__item' do
      %li 発送元・お届け先情報変更
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to new_user_card_path(current_user.id),method: :get, class: 'mypage__main__mask__left__nav-list__item' do
      %li 支払い方法
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li メール/パスワード
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li 本人情報
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to '#', class: 'mypage__main__mask__left__nav-list__item' do
      %li 電話番号の確認
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')
    = link_to destroy_user_session_path, method: :delete, class: 'mypage__main__mask__left__nav-list__item' do
      %li ログアウト
      = icon("fa", "angle-right", class: 'mypage__main__mask__left__nav-list__item__arrow')

app/views/shared/_sellbtn.html.haml
= link_to new_item_path do  
  .sell-btn
    %p.sell-btn__text 出品する
    = image_tag("material/icon/icon_camera.png", class: 'sell-btn__icon')

app/views/shared/_sub_footer.html.haml
.sub-footer
  .sub-footer__box
    %ul.sub-footer__box__menu
      %li.sub-footer__box__menu__privacy
        = link_to "#" do
          プライバシーポリシー
      %li.sub-footer__box__menu__kiyaku
        = link_to "#" do
          メルカリ利用規約
      %li.sub-footer__box__menu__torihiki
        = link_to "#" do
          特定商取引に関する表記
    = link_to root_path  do
      = image_tag "material/logo/logo.png", class:"sub-footer__box__image"
      .sub-footer__box__bottom
        © Furima, Inc.

app/views/shared/_sub_header.html.haml
.devise-header__image
  = link_to root_path  do
    = image_tag "material/logo/logo.png", class:"devise-header__image__icon" 