config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    # resources :purchases, only: [:index, :create, :show]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    resources :purchases, only: [:index, :create] do
      collection do
        post 'pay'
        get 'done'
      end
    end
  end
  resources :users, only: [:show] do
    resources :residences, only: [:create, :index]
    resources :card, only: [:new, :index] do
      collection do
        post 'pay', to: 'card#pay'
        delete 'delete', to: 'card#delete'
      end
    end
  end
  root "items#index"
  
  resources :categories, only: [:index]
  
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  # association
  belongs_to :user
  belongs_to :category
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  # belongs_to :category

  # validation
  validates :name,             presence: true, length: {maximum: 40}
  validates :price,            presence: true
  validates :content,          presence: true, length: {maximum: 1000}
  validates :condition,        presence: true
  validates :shipping,         presence: true
  validates :shipping_area,    presence: true
  validates :days_to_ship,     presence: true
  validates :shipping_method,  presence: true
  validates :status,           presence: true
  validates :category_id_1,    presence: true
  validates :category_id_2,    presence: true
  validates :category_id_3,    presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only:[:destroy, :show, :edit, :update]
  before_action :move_to_login, only:[:new, :create, :edit, :update, :destroy]

  def index
    @items = Item.all.order("created_at DESC")
    @item_images = ItemImage.all
    # @parents = Category.order("id ASC").limit(13)
  end
  def new
    if user_signed_in?
      @item = Item.new
      @item.item_images.new
    else
      redirect_to new_user_session_path
    end
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
  end

  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def get_size
    #選択された子カテゴリーに紐付くひ孫カテゴリーの配列を取得
    @size = Category.find("#{params[:grandchild_id]}").children
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @parents = Category.order("id ASC").limit(13)
    @category_1 = Category.find(@item.category_id_1)
    @category_2 = Category.find(@item.category_id_2)
    @category_3 = Category.find(@item.category_id_3)
    unless @item.size_id.nil?
      @size = Category.find(@item.size_id)
    end

  end

  def edit
    @category_2 = Category.find(@item.category_id_2) if @item.category_id_2
    @category_3 = Category.find(@item.category_id_3) if @item.category_id_3
    @size = Category.find(@item.size_id) if @item.size_id
  end

  def update
    if @item.update(item_edit_params)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    render :delete unless @item.user_id == current_user.id && @item.destroy
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :content, :brand, :condition, :shipping, :shipping_area, :days_to_ship, :shipping_method, :status,:category_id_1,:category_id_2, :category_id_3, :size_id,  item_images_attributes: [:image]).merge(user_id: current_user.id).merge(status: 1).merge(category_id: params[:item][:category_id_3])
  end

  def item_edit_params
    params.require(:item).permit(:id, :category_id, :name, :price, :content, :brand, :condition, :shipping, :shipping_area, :days_to_ship, :shipping_method, :status,:category_id_1,:category_id_2, :category_id_3, :size_id,  item_images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id).merge(status: 1).merge(category_id: params[:item][:category_id_3])
  end

  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_banner.html.haml
.banner
  .banner__content
    %h2.title
      = title
    .sub-title
      %pre
        = sub
    .app-btns
      = link_to "#" do
        = image_tag 'app/app-store.svg', class: "app-btn"
      = link_to "#" do
        = image_tag 'app/google-play.svg', class: "app-btn"

app/views/items/_index_banner.html.haml
.banner
  .banner__content
    %h2.title
      = title
    .sub-title
      %pre
        = sub
    .app-btns
      = link_to "#" do
        = image_tag '/assets/app/app-store.svg', class: "app-btn"
      = link_to "#" do
        = image_tag '/assets/app/google-play.svg', class: "app-btn"

app/views/items/_index_item.html.haml
.item 
  %a.item__link(href = "#")
  .item__image  
    = image_tag "/assets/material/pict/pict-reason-01.jpg", class: "item-image"
  .item__body
    .item__body--name
      iPhone 11 pro
    .item__body--middle
      .item__body--middle__price
        100円
      .item__body--middle__favorite
        = link_to "#" do
          %i.fa.fa-star
        %p 0
    .item__body--fee
      (税込)

app/views/items/_item.html.haml
- if item.status == 1
  .item 
    = link_to item_path(item.id) do
      .item__image 
        - objects = item.item_images
        - first_image = objects.first 
        = image_tag first_image.image.url , class: "item-image"
        
      .item__body
        .item__body--name
          = item.name
        .item__body--middle
          .item__body--middle__price
            = "¥#{item.price.to_s(:delimited)}"
          .item__body--middle__favorite
            = link_to "#" do
              %i.fa.fa-star
            %p.favorit-number 0
        .item__body--fee
          (税込)
- else
  .item
    = link_to item_path(item.id) do
      .item__image 
        - objects = item.item_images
        - first_image = objects.first 
        = image_tag first_image.image.url , class: "item-image"
      .sold-cover
      %p.sold sold
        
      .item__body
        .item__body--name
          = item.name
        .item__body--middle
          .item__body--middle__price
            = "¥#{item.price.to_s(:delimited)}"
          .item__body--middle__favorite
            = link_to "#" do
              %i.fa.fa-star
            %p.favorit-number 0
        .item__body--fee
          (税込)

app/views/items/destroy.html.haml
= render partial: "shared/header"
.main
  .main__area
    .main__area__destroy-box
      %p 削除が完了しました。
      = link_to root_path do
        = label_tag '', '商品一覧へ戻る', {class: 'main__area__destroy-box__btn'}


  .bottom-banner
    = render partial: "banner", locals: {title: "だれでもかんたん、人生を変えるフリマアプリ", sub: "今すぐ無料ダウンロード！"}
  .main__footer
    = render "shared/footer"

app/views/items/index.html.haml
.header
  = render "/shared/header"
.main
  .top-banner
    = render partial: "banner", locals: {title: "人生を変えるフリマアプリ", sub: "FURIMAはだれでもかんたんに出品・購入できる\nフリマアプリです"}
  .introduction
    .introduction__reason-for-chose
      FURIMAが選ばれる3つの理由
    .introduction__reason-lists
      .lists
        .lists__list
          .lists__list--picture
            %p.number 1
            = image_tag 'material/pict/pict-reason-01.jpg', class: "reason-picture"
          .lists__list--text
            %span 3分
            ですぐに出品
          .lists__list--discription
            スマホで入力するだけで簡単に出品できる！
        .lists__list
          .lists__list--picture
            %p.number 2
            = image_tag 'material/pict/pict-reason-02.jpg', class: "reason-picture"
          .lists__list--text
            %span シンプル
            で使いやすい
          .lists__list--discription
            めんどくさい入力は必要なく、検索も購入もスムーズ！
        .lists__list
          .lists__list--picture
            %p.number 3
            = image_tag 'material/pict/pict-reason-03.jpg', class: "reason-picture"
          .lists__list--text
            手数料
            %span 業界最安
          .lists__list--discription
            最大3%でお得に出品&購入！

  .middle-banner
    = render partial: "banner", locals: {title: "会員数日本一位", sub: "FURIMAは、フリマアプリで最も人気。\n出品・購入回数も業界最多です！\nほしかったあの商品に出会えるかもしれません。"}

  .feature
    .feature__title
      FURIMAの特徴
    .feature__feature-lists 
      .list
        .list__picture
          = image_tag 'material/icon/icon-01.png', class: "feature-picture"
        .list__text
          簡単に売り買いできる
        .list__discription
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .list
        .list__picture
          = image_tag 'material/icon/icon-03.png', class: "feature-picture"
        .list__text
          売上金は即日振込みに対応
        .list__discription
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .list
        .list__picture
          = image_tag 'material/icon/icon-04.png', class: "feature-picture"
        .list__text
          様々な支払いに対応
        .list__discription
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  
  .pic-up
    .pic-up__title
      ピックアップ

    .pic-up__content
      = link_to '商品一覧', "#", class: "item-links"
      - if @item_images.present?
        .items
          = render @items
      

  .bottom-banner
    = render partial: "banner", locals: {title: "だれでもかんたん、人生を変えるフリマアプリ", sub: "今すぐ無料ダウンロード！"}
    

.footer
  = render "shared/footer"

.sellbtn
  = render "shared/sellbtn"

app/views/items/new.html.haml
.product-listings-page
  .product-listings-page__header
    = render "/shared/sub_header"
  .product-listings-page__main
    .product-listings-page__main__contents
      .product-listings-page__main__contents__head
        %h2.product-listings-page__main__contents__head__text 商品の情報を入力
      = form_with model: @item, local: true, class:"product-listings-page__main__contents__form" do |form|
        .product-listings-page__main__contents__photo-box
          .product-listings-page__main__contents__photo-box__title
            %h3.product-listings-page__main__contents__photo-box__title__left 出品画像
            %span.product-listings-page__main__contents__photo-box__title__right 必須
          %p.product-listings-page__main__contents__photo-box__text 最大10枚までアップロードできます

          #image-box
            #previews
              - if @item.persisted?
                - @item.item_images.each_with_index do |image, i|
                  - id_str = 'image-' + (i).to_s
                  = image_tag image.src.url, id: id_str ,data: {index: i}, width: '118', height: '118'
            #file-box
              = form.fields_for :item_images do |image|
                .js-file_group{data: {index: image.index}}
                  = image.label :image, data: {index: image.index} do
                    %svg{"aria-hidden" => "true", :fill => "#222222", "fill-rule" => "evenodd", :height => "24", :viewbox => "0 0 24 24", :width => "24"}
                      %path{:d => "M19.3,5H16.73l-.8-1.61A.7.7,0,0,0,15.3,3H8.7a.7.7,0,0,0-.63.39L7.27,5H4.7A2.7,2.7,0,0,0,2,7.7V18.3A2.7,2.7,0,0,0,4.7,21H19.3A2.7,2.7,0,0,0,22,18.3V7.7A2.7,2.7,0,0,0,19.3,5ZM12,17.3A4.3,4.3,0,1,1,16.3,13,4.31,4.31,0,0,1,12,17.3Z"}

                    = image.file_field :image, class: 'js-file'
                  %span.js-remove.hoge 削除
                - if @item.persisted?
                  = image.check_box :_destroy, data: {index: image.index}, class: 'hidden-destroy'
              - if @item.persisted?
                .js-file_group{"data-index" => "#{@item.item_images.count}"}
                  = file_field_tag :image, name: "item[item_images_attributes][#{@item.images.count}][image]", class: 'js-file'
                  .js-remove 削除
          %span#image_error.error_m

        .product-listings-page__main__contents__name-box
          .product-listings-page__main__contents__name-box__title
            .product-listings-page__main__contents__name-box__title__left 商品名
            %span.product-listings-page__main__contents__name-box__title__right 必須
          =form.text_field :name, class:"product-listings-page__main__contents__name-box__text-field", placeholder:"商品名（必須40文字まで）"
          %span#name_error.error_m
          .product-listings-page__main__contents__name-box__title-2
            .product-listings-page__main__contents__name-box__title__left 商品の説明
            %span.product-listings-page__main__contents__name-box__title__right 必須
          =form.text_area :content, class:"product-listings-page__main__contents__name-box__text-area", placeholder:"商品の説明（必須 1,000文字以内）&#13;&#10;色、素材、重さ、定価、注意点などを記載してください。&#13;&#10;&#13;&#10;例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。".html_safe 
          %span#content_error.error_m
        .product-listings-page__main__contents__detail-box
          %h3.product-listings-page__main__contents__detail-box__title 商品の詳細
          .product-listings-page__main__contents__detail-box__select-list
            .product-listings-page__main__contents__detail-box__select-list__title
              .product-listings-page__main__contents__detail-box__select-list__title__left カテゴリー
              %span.product-listings-page__main__contents__detail-box__select-list__title__right 必須
            .product-listings-page__main__contents__detail-box__select-list__category-form
              .product-listings-page__main__contents__detail-box__select-list__category-form--first
                = form.select :category_id_1, {"---":0, "レディース":1, "メンズ":2, "ベビー・キッズ":3, "インテリア・住まい・小物":4, "本・音楽・ゲーム":5, "おもちゃ・ホビー・グッズ":6, "コスメ・香水・美容":7, "家電・スマホ・カメラ":8, "スポーツ・レジャー":9, "ハンドメイド":10, "チケット":11, "自転車・オートバイ":12, "その他":13}, {}, {class: 'product-listings-page__main__contents__detail-box__select-list__category-form--first__value', id: 'parent_category'}
                = icon('fas', 'chevron-down', class: "product-listings-page__main__contents__detail-box__select-list__category-form--first__icon")
              %span#category_error.error_m
            .product-listings-page__main__contents__detail-box__select-list__title-brand
              .product-listings-page__main__contents__detail-box__select-list__title__left ブランド
              %span.product-listings-page__main__contents__detail-box__select-list__title__right--not-required 任意
            .product-listings-page__main__contents__detail-box__select-list__brand-form
              =form.text_field :brand, class:"product-listings-page__main__contents__detail-box__select-list__brand-form__value", placeholder:"例）シャネル"
            .product-listings-page__main__contents__detail-box__select-list__title-condition
              .product-listings-page__main__contents__detail-box__select-list__title__left 商品の状態
              %span.product-listings-page__main__contents__detail-box__select-list__title__right 必須
            .product-listings-page__main__contents__detail-box__select-list__condition-form
              =form.select :condition, {"---":"---", "新品、未使用":"新品、未使用", "未使用に近い":"未使用に近い", "目立った傷や汚れなし":"目立った傷や汚れなし", "やや傷や汚れあり":"やや傷や汚れあり", "傷や汚れあり":"傷や汚れあり", "全体的に状態が悪い":"全体的に状態が悪い"}, {},  class: 'product-listings-page__main__contents__detail-box__select-list__condition-form__value'
              = icon('fas', 'chevron-down', class: "product-listings-page__main__contents__detail-box__select-list__condition-form__icon")
            %span#condition_error.error_m

        .product-listings-page__main__contents__delivery-box
          %h3.product-listings-page__main__contents__delivery-box__title 配送について
          = link_to "#",  class:"product-listings-page__main__contents__delivery-box__title__question" do
            ?
          .product-listings-page__main__contents__delivery-box__select-list
            .product-listings-page__main__contents__delivery-box__select-list__title
              .product-listings-page__main__contents__delivery-box__select-list__title__left 配送料の負担
              %span.product-listings-page__main__contents__delivery-box__select-list__title__right 必須
            .product-listings-page__main__contents__delivery-box__select-list__shipping-form
              =form.select :shipping, {"---":"---", "送料込み(出品者負担)":"送料込み(出品者負担)", "着払い(購入者負担)":"着払い(購入者負担)"}, {},  class: 'product-listings-page__main__contents__delivery-box__select-list__shipping-form__value'
              = icon('fas', 'chevron-down', class: "product-listings-page__main__contents__delivery-box__select-list__shipping-form__icon")
            %span#shipping_error.error_m
            .product-listings-page__main__contents__delivery-box__select-list__title-method
              .product-listings-page__main__contents__delivery-box__select-list__title__left 配送の方法
              %span.product-listings-page__main__contents__delivery-box__select-list__title__right 必須
            .product-listings-page__main__contents__delivery-box__select-list__method-form
              =form.select :shipping_method, {"---":"---","らくらくメルカリ便":"らくらくメルカリ便", "ゆうメール":"ゆうメール", "レターパック":"レターパック", "普通郵便（定型、定形外）":"普通郵便（定型、定形外）", "クロネコヤマト":"クロネコヤマト", "ゆうパック":"ゆうパック", "クリックポスト":"クリックポスト", "ゆうパケット":"ゆうパケット" }, {},  class: 'product-listings-page__main__contents__delivery-box__select-list__method-form__value'
              = icon('fas', 'chevron-down', class: "product-listings-page__main__contents__delivery-box__select-list__method-form__icon")
            %span#shipping_method_error.error_m
            .product-listings-page__main__contents__delivery-box__select-list__title-area
              .product-listings-page__main__contents__delivery-box__select-list__title__left 発送元の地域
              %span.product-listings-page__main__contents__delivery-box__select-list__title__right 必須
            .product-listings-page__main__contents__delivery-box__select-list__area-form
              =form.collection_select :shipping_area, Prefecture.all, :name, :name, {}, prompt: "---", class: 'product-listings-page__main__contents__delivery-box__select-list__area-form__value'
              = icon('fas', 'chevron-down', class: "product-listings-page__main__contents__delivery-box__select-list__area-form__icon")
            %span#shipping_area_error.error_m
            .product-listings-page__main__contents__delivery-box__select-list__title-days
              .product-listings-page__main__contents__delivery-box__select-list__title__left 発送までの日数
              %span.product-listings-page__main__contents__delivery-box__select-list__title__right 必須
            .product-listings-page__main__contents__delivery-box__select-list__days-form
              =form.select :days_to_ship, {"---":"---", "１〜２日で発送":"１〜２日で発送", "２〜３日で発送":"２〜３日で発送", "４〜７日で発送":"４〜７日で発送"}, {},  class: 'product-listings-page__main__contents__delivery-box__select-list__days-form__value'
              = icon('fas', 'chevron-down', class: "product-listings-page__main__contents__delivery-box__select-list__days-form__icon")
            %span#days_to_ship_error.error_m

        .product-listings-page__main__contents__price-box
          %h3.product-listings-page__main__contents__price-box__title 販売価格(300〜9,999,999)
          = link_to "#",  class:"product-listings-page__main__contents__price-box__title__question" do
            ?
          .product-listings-page__main__contents__price-box__form-box
            %ul.product-listings-page__main__contents__price-box__form-box__lists
              %li.product-listings-page__main__contents__price-box__form-box__lists-price
                .product-listings-page__main__contents__price-box__form-box__lists-price-left
                  .product-listings-page__main__contents__price-box__form-box__lists-price-left__title 価格
                  %span.product-listings-page__main__contents__price-box__form-box__lists-price-left__title-right 必須
                .product-listings-page__main__contents__price-box__form-box__lists-price-right
                  .product-listings-page__main__contents__price-box__form-box__lists-price-right__text ¥
                  =form.text_field :price, class:"product-listings-page__main__contents__price-box__form-box__lists-price-right__form ", placeholder:"例）300"
              %p#price_error.error_m
              %li.product-listings-page__main__contents__price-box__form-box__lists-fee
                .product-listings-page__main__contents__price-box__form-box__lists-fee-left 販売手数料(10%)
                .product-listings-page__main__contents__price-box__form-box__lists-fee-right -
              %li.product-listings-page__main__contents__price-box__form-box__lists-interests
                .product-listings-page__main__contents__price-box__form-box__lists-interests-left 販売利益
                .product-listings-page__main__contents__price-box__form-box__lists-interests-right -


        .product-listings-page__main__contents__send-box
          .product-listings-page__main__contents__send-box__text
            = link_to "#" do
              禁止されている出品
            、
            = link_to "#" do
              行為
            を必ずご確認ください。
          .product-listings-page__main__contents__send-box__text
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            = link_to "#" do
              偽ブランド
            の販売は犯罪であり処罰される可能性があります。
          .product-listings-page__main__contents__send-box__text
            また、出品をもちまして
            = link_to "#" do
              加盟店規約
            に同意したことになります。
          =form.submit "出品する", class: "product-listings-page__main__contents__send-box__btn"
          .product-listings-page__main__contents__send-box__return-btn
            = link_to root_path do
              もどる

= render "/shared/sub_footer"

app/views/items/show.html.haml
= render partial: "shared/header"
.main
  .main__show
    .main__show__content
      .main__show__content__top
        .main__show__content__top__itemInfo
          .main__show__content__top__itemInfo__name
            = @item.name
          .main__show__content__top__itemInfo__image
            %ul.main__show__content__top__itemInfo__image__ul
              - objects = @item.item_images
              - objects.each do |object| 
                %li.main__show__content__top__itemInfo__image__ul__li
                  = image_tag object.image.url, class: "main__show__content__top__itemInfo__image__ul__li__img "
                  - if @item.status == 0
                    .show-sold-cover
                    %p.show-sold sold
            .custom-thumb
          .main__show__content__top__itemInfo__price
            %span.main__show__content__top__itemInfo__price__span
              = "¥#{@item.price.to_s(:delimited)}"
            .main__show__content__top__itemInfo__price__detail
              %span.main__show__content__top__itemInfo__price__detail__span
                (税込み)
              %span.main__show__content__top__itemInfo__price__detail__span
                送料込み
          - if @item.status == 1 && user_signed_in?
            - unless current_user.id == @item.user_id
              .main__show__content__top__itemInfo__purchase
                = link_to '購入画面に進む', item_purchases_path(params[:id]), class: "main__show__content__top__itemInfo__purchase__link"
          .main__show__content__top__itemInfo__detail
            = @item.name
          .main__show__content__top__itemInfo__table
            %table.main__show__content__top__itemInfo__table__table
              %tbody.main__show__content__top__itemInfo__table__table__tbody
                %tr.main__show__content__top__itemInfo__table__table__tbody__tr
                  %th.main__show__content__top__itemInfo__table__table__tbody__tr__th
                    出品者
                  %td.main__show__content__top__itemInfo__table__table__tbody__tr__td
                    = @item.user.nickname
                %tr.main__show__content__top__itemInfo__table__table__tbody__tr
                  %th.main__show__content__top__itemInfo__table__table__tbody__tr__th
                    カテゴリー
                  %td.main__show__content__top__itemInfo__table__table__tbody__tr__td
                    %ul
                      %li
                        = link_to "#{@category_1.name}", "#", class: "main__show__content__top__itemInfo__table__table__tbody__tr__td__link" 
                      %li
                        = link_to "#{@category_2.name}", "#", class: "main__show__content__top__itemInfo__table__table__tbody__tr__td__link" 
                      %li
                        = link_to "#{@category_3.name}", "#", class: "main__show__content__top__itemInfo__table__table__tbody__tr__td__link" 
                %tr.main__show__content__top__itemInfo__table__table__tbody__tr
                  %th.main__show__content__top__itemInfo__table__table__tbody__tr__th
                    ブランド
                  %td.main__show__content__top__itemInfo__table__table__tbody__tr__td
                    = @item.brand
                %tr.main__show__content__top__itemInfo__table__table__tbody__tr
                  %th.main__show__content__top__itemInfo__table__table__tbody__tr__th
                    商品のサイズ
                  %td.main__show__content__top__itemInfo__table__table__tbody__tr__td
                    - unless @size.nil?
                      = @size.name
                %tr.main__show__content__top__itemInfo__table__table__tbody__tr
                  %th.main__show__content__top__itemInfo__table__table__tbody__tr__th
                    商品の状態
                  %td.main__show__content__top__itemInfo__table__table__tbody__tr__td
                    = @item.condition
                %tr.main__show__content__top__itemInfo__table__table__tbody__tr
                  %th.main__show__content__top__itemInfo__table__table__tbody__tr__th
                    配送料の負担
                  %td.main__show__content__top__itemInfo__table__table__tbody__tr__td
                    = @item.shipping
                %tr.main__show__content__top__itemInfo__table__table__tbody__tr
                  %th.main__show__content__top__itemInfo__table__table__tbody__tr__th
                    発送元の地域
                  %td.main__show__content__top__itemInfo__table__table__tbody__tr__td
                    = @item.shipping_area
                %tr.main__show__content__top__itemInfo__table__table__tbody__tr
                  %th.main__show__content__top__itemInfo__table__table__tbody__tr__th
                    発送日の目安
                  %td.main__show__content__top__itemInfo__table__table__tbody__tr__td
                    = @item.days_to_ship
          .main__show__content__top__itemInfo__other  
            %ul.main__show__content__top__itemInfo__other__left
              %li.main__show__content__top__itemInfo__other__left__btn
                = icon('fa','star',class: "main__show__content__top__itemInfo__other__left__btn__icon")
                お気に入り 0
            %ul.main__show__content__top__itemInfo__other__right
              %li.main__show__content__top__itemInfo__other__right__list
                = link_to "#", class: "main__show__content__top__itemInfo__other__right__list__btn" do
                  = icon('fa','flag', class: "main__show__content__top__itemInfo__other__right__list__btn__icon")
                  不適切な商品の通報
        - if user_signed_in? && current_user.id == @item.user_id
          .main__show__content__top__itemUser
            .main__show__content__top__itemUser__edit
              = link_to "商品の編集", edit_item_path(@item), class: "main__show__content__top__itemUser__edit__link"
            .main__show__content__top__itemUser__destroy
              = link_to "この商品を削除する", item_path(@item), method: :delete, class: "main__show__content__top__itemUser__destroy__link"
        .main__show__content__top__commentArea
          %form{action: "#", class: "main__show__content__top__commentArea__form"}
            %textarea.main__show__content__top__commentArea__form__textarea
            %p.main__show__content__top__commentArea__message
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %br
            %button{name: "button", type: "submit", class: "main__show__content__top__commentArea__btn"}
              = icon('fa', 'comment',class: "main__show__content__top__commentArea__btn__icon")
              コメントする
        %ul.main__show__content__top__aroundItems
          %li.main__show__content__top__aroundItems__before
            = link_to "#", class: "main__show__content__top__aroundItems__before__link" do
              = icon('fa', 'angle-left', class: "main__show__content__top__aroundItems__before__link__icon")
              前の商品
          %li.main__show__content__top__aroundItems__after
            = link_to  "#", class: "main__show__content__top__aroundItems__after__link"  do
              後ろの商品
              = icon('fa', 'angle-right', class: "main__show__content__top__aroundItems__after__link__icon")
        .main__show__content__top__moreItems
          = link_to "ベビーキッズをもっと見る", "#", class: "main__show__content__top__moreItems__link"
  .bottom-banner
    = render partial: "banner", locals: {title: "だれでもかんたん、人生を変えるフリマアプリ", sub: "今すぐ無料ダウンロード！"}
  .main__footer
    = render "shared/footer"

.sellbtn
  = render "shared/sellbtn"