config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    # resources :purchases, only: [:index, :create, :show]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    resources :purchases, only: [:index, :create] do
      collection do
        post 'pay'
        get 'done'
      end
    end
  end
  resources :users, only: [:show] do
    resources :residences, only: [:create, :index]
    resources :card, only: [:new, :index] do
      collection do
        post 'pay', to: 'card#pay'
        delete 'delete', to: 'card#delete'
      end
    end
  end
  root "items#index"
  
  resources :categories, only: [:index]
  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  before_action :move_to_login, only:[:new, :pay, :delete, :index]
  before_action :set_card

  def new
    card = set_card
    redirect_to action: "index" if card.exists?
  end

  def pay
    card = set_card
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    if params['payjp-token'].blank?
      if session[:item_id].nil?
        redirect_to user_card_index_path(current_user.id)
      else
        redirect_to item_purchases_path(item_id: session[:item_id])
      end
    else
      customer = Payjp::Customer.create(
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      @card.save
      if session[:item_id].nil?
        redirect_to new_user_card_path(current_user.id)
      else
        redirect_to item_purchases_path(item_id: session[:item_id])
      end
    end
  end

  def delete 
    card = set_card.first
    if card.present?
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def index
    card = set_card.first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @default_card_brand = @default_card_information.brand      
      case @default_card_brand
      when "Visa"
        @default_card_src = "visa.png"
      when "JCB"
        @default_card_src = "jcb.png"
      when "MasterCard"
        @default_card_src = "master.png"
      when "American Express"
        @default_card_src = "american.png"
      when "Diners Club"
        @default_card_src = "dinersclub.png"
      when "Discover"
        @default_card_src = "discover.png"
      end
    end
  end

  private

  def set_card
    Card.where(user_id: current_user.id)
  end

  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/index.html.haml
.card
  = render partial: "/shared/header"
  .card__card-main
    .card__card-main__mask
      = render partial:"/shared/mypage-left"
      .card__card-main__mask__contents
        .card__card-main__mask__contents__header
          支払い方法
        .card__card-main__mask__contents__content
          .card__card-main__mask__contents__content__theme
            登録クレジットカード情報
          .card__card-main__mask__contents__content__menu
            = image_tag "material/credit/#{@default_card_src}", width: '40', height: '25', alt: @default_card_brand, id: "card_image",class:"card__card-main__mask__contents__content__menu__brand"
            .card__card-main__mask__contents__content__menu__number
            = "**** **** **** " + @default_card_information.last4
            .card__card-main__mask__contents__content__menu__date
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            .card__card-main__mask__contents__content__menu__delete
            = form_tag(delete_user_card_index_path(user_id: current_user.id), method: :delete, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button.card__card-main__mask__contents__content__menu__delete__btn 削除する
          .card__card-main__mask__contents__content__info
            = link_to "#", class: "card__card-main__mask__contents__content__info__text" do
              支払い方法について　＞
  .mypage__footer
    = render "/shared/footer"

  = render partial: "/shared/sellbtn"

app/views/card/new.html.haml
.card
  = render partial: "/shared/header"
  .card__card-main
    .card__card-main__mask
      = render partial:"/shared/mypage-left"
      .card__card-main__mask__contents
        .card__card-main__mask__contents__header
          支払い方法
        .card__card-main__mask__contents__body
          = form_tag(pay_user_card_index_path(current_user.id), method: :post, id: 'charge-form',  name: "inputForm") do
            .card__card-main__mask__contents__body__card
              .card__card-main__mask__contents__body__card__top
                #hold_error.error_m
                .card__card-main__mask__contents__body__card__top__line
                  .card__card-main__mask__contents__body__card__top__line__left
                    カード番号
                  .card__card-main__mask__contents__body__card__top__line__right
                    必須
              .card__card-main__mask__contents__body__card__middle
                = text_field_tag "number", "", class: "card__card-main__mask__contents__body__card__middle__box", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              #card_error.error_m
              .card__card-main__mask__contents__body__card__bottom
                = image_tag "material/logo/credit.png", class:"card__card-main__mask__contents__body__card__bottom__icon__credit"
            .card__card-main__mask__contents__body__effective
              .card__card-main__mask__contents__body__effective__top
                .card__card-main__mask__contents__body__effective__top__left
                  有効期限
                .card__card-main__mask__contents__body__effective__top__right
                  必須
              .card__card-main__mask__contents__body__effective__bottom
                .card__card-main__mask__contents__body__effective__bottom__month
                  = icon('fas', 'chevron-down', class: "card__card-main__mask__contents__body__effective__bottom__month__icon")
                  %select#exp_month{name: "exp_month", type: "text", class:"card__card-main__mask__contents__body__effective__bottom__month__select"}
                    %option{value: ""} --
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                %p.card__card-main__mask__contents__body__effective__bottom__month__text 月
                .card__card-main__mask__contents__body__effective__bottom__year
                  = icon('fas', 'chevron-down', class: "card__card-main__mask__contents__body__effective__bottom__year__icon")
                  %select#exp_year{name: "exp_year", type: "text", class:"card__card-main__mask__contents__body__effective__bottom__year__select"}
                    %option{value: ""} --
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                %p.card__card-main__contents__body__effective__bottom__year__text 年
              %span#effective_error.error_m
            .card__card-main__mask__contents__body__security
              .card__card-main__mask__contents__body__security__top
                .card__card-main__mask__contents__body__security__top__left
                  セキュリティーコード
                .card__card-main__mask__contents__body__security__top__right
                  必須
              .card__card-main__mask__contents__body__security__bottom
                = text_field_tag "cvc", "", class: "card__card-main__mask__contents__body__security__bottom__box", placeholder: "カード背面４桁もしくは３桁の番号", maxlength: "4", id: "cvc"
                .card__card-main__mask__contents__body__security__bottom__note
                  #cvc_error.error_m
                  = link_to "#note1", class:"card__card-main__mask__contents__body__security__bottom__note__question" do
                    ?
                  = link_to "#note1", class:"card__card-main__mask__contents__body__security__bottom__note__text" do
                    カード裏面の番号とは？
                  %p{class:'card__card-main__mask__contents__body__security__bottom__note__tooltip',id:'note1'}
                    カードの裏面をご参照ください。
                    = image_tag "material/credit/note.png", width: '240', height: '105'
            .card__card-main__mask__contents__body__btn
              #card_token
              = submit_tag "登録する", id: "token_submit", class:"card__card-main__mask__contents__body__btn__box"
  .mypage__footer
    = render "/shared/footer"

  = render partial: "/shared/sellbtn"

app/views/card/show.html.haml
.devise-header
  = render "/shared/sub_header"
.card-main
  .card-main__contents
    .card-main__contents__header
      支払い方法
    .card-main__contents__content
      .card-main__contents__content__theme
        登録クレジットカード情報
      .card-main__contents__content__menu
        = image_tag "/assets/material/credit/#{@default_card_src}", width: '40', height: '25', alt: @default_card_brand, id: "card_image",class:"card-main__contents__content__menu__brand"
        .card-main__contents__content__menu__number
        = "**** **** **** " + @default_card_information.last4
        .card-main__contents__content__menu__date
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
        .card-main__contents__content__menu__delete
        = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button.card-main__contents__content__menu__delete__btn 削除する
      .card-main__contents__content__info
        = link_to "#", class: "card-main__contents__content__info__text" do
          支払い方法について　＞
= render "/shared/sub_footer"